version: '3'
services:
  app:
    container_name: go-bank
    image: go-bank:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - bank_net
  db:
    container_name: bank-db
    image: postgres:latest
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - bank_net
networks:
  bank_net: